- name: Create MariaDB database
  community.mysql.mysql_db:
    name: "{{ mariadb_database }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create MariaDB user
  community.mysql.mysql_user:
    name: "{{ mariadb_username }}"
    password: "{{ mariadb_password }}"
    priv: "{{ mariadb_db_name }}.*:ALL"
    host: "{{ mariadb_host }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Check for existing sample data
  ansible.builtin.stat:
  path: /tmp/sample_data.sql
  register: sample_data_check

# Step 0: Copy sample data file to the target host if not exists
- name: Copy sample data (if missing)
  ansible.builtin.copy:
    src: /home/ec2-user/Angular-Static-Website/sample-data/contact-data.sql
    dest: /tmp/sample_data.sql
    mode: '0644'
  when: not sample_data_check.stat.exists
  register: copy_task

- name: Verify SQL file exists
  ansible.builtin.stat:
    path: /tmp/sample_data.sql
  register: sample_data_verify
  always_run: yes  # Critical for proper validation
  
- name: Import sample data
  community.mysql.mysql_db:
    name: "{{ mariadb_database }}"
    state: import
    target: /tmp/sample_data.sql
    login_unix_socket: /var/run/mysqld/mysqld.sock
  when: sample_data_verify.stat.exists