---
- name: Create MariaDB database
  community.mysql.mysql_db:
    name: "{{ mariadb_database }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create MariaDB user
  community.mysql.mysql_user:
    name: "{{ mariadb_user }}"
    password: "{{ mariadb_password }}"
    priv: "{{ mariadb_database }}.*:ALL"
    host: "{{ mariadb_host }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Ensure sample data file exists
  stat:
    path: /tmp/sample_data.sql
  register: sample_data_file