---
- name: Create MariaDB database
  community.mysql.mysql_db:
    name: "{{ mariadb_database }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Delete all users from the users table
  community.mysql.mysql_query:
    login_user: root
    login_password: "{{ mariadb_password }}"
    login_db: angular_app_db
    query: "DELETE FROM users;"

- name: Create MariaDB user
  community.mysql.mysql_user:
    name: "{{ mariadb_user }}"
    password: "{{ mariadb_password }}"
    priv: "{{ mariadb_database }}.*:ALL"
    host: "{{ mariadb_host }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Ensure sample data file exists
  stat:
    path: /tmp/sample_data.sql
  register: sample_data_file

- name: Check if users table exists
  community.mysql.mysql_query:
    query: "SELECT COUNT(*) AS table_exists FROM INFORMATION_SCHEMA.TABLES WHERE table_schema = '{{ mariadb_database }}' AND table_name = 'users'"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  register: table_check

- name: Process sample data import
  block:
    - name: Check for existing index
      community.mysql.mysql_query:
        query: |
          SELECT COUNT(*) AS index_exists 
          FROM INFORMATION_SCHEMA.STATISTICS 
          WHERE table_schema = '{{ mariadb_database }}' 
          AND table_name = 'users' 
          AND index_name = 'idx_username'
        login_unix_socket: /var/run/mysqld/mysqld.sock
      register: index_check

    - name: Modify SQL file if index exists
      replace:
        path: /tmp/sample_data.sql
        regexp: '^CREATE INDEX idx_username ON users\(username\)'
        replace: '-- Index already exists'
      when: index_check.query_result[0].index_exists > 0

    - name: Import sample data
      ansible.builtin.mysql_db:
        name: "{{ mariadb_database }}"
        state: import
        target: /tmp/sample_data.sql
        login_unix_socket: /var/run/mysqld/mysqld.sock
      ignore_errors: true
  when: table_check.query_result[0].table_exists == 1 and sample_data_file.stat.exists
