- name: Create MariaDB database
  community.mysql.mysql_db:
    name: "{{ mariadb_database }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create MariaDB user
  community.mysql.mysql_user:
    name: "{{ mariadb_username }}"
    password: "{{ mariadb_password }}"
    priv: "{{ mariadb_db_name }}.*:ALL"
    host: "{{ mariadb_host }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Import sample data (if available)
  block:
    - name: Check if sample data exists
      stat:
        path: /tmp/sample_data.sql
      register: sample_data_file

- name: Import sample data (if available)
  community.mysql.mysql_db:
    name: "{{ mariadb_database }}"
    state: import
    target: /tmp/sample_data.sql
    login_unix_socket: /var/run/mysqld/mysqld.sock