---
- name: Create MariaDB database
  community.mysql.mysql_db:
    name: "{{ mariadb_database }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create MariaDB user
  community.mysql.mysql_user:
    name: "{{ mariadb_user }}"
    password: "{{ mariadb_password }}"
    priv: "{{ mariadb_database }}.*:ALL"
    host: "{{ mariadb_host }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Ensure sample data file exists
  stat:
    path: /tmp/sample_data.sql
  register: sample_data_file

<<<<<<< HEAD
# Step 1: Copy sample data file if it doesn't already exist
- name: Copy sample data file to target server
  copy:
    src: files/sample_data.sql
    dest: /tmp/sample_data.sql
    mode: '0644'
  when: not sample_data_file.stat.exists
=======
- name: Check if users table exists
  community.mysql.mysql_query:
    query: "SELECT COUNT(*) AS table_exists FROM INFORMATION_SCHEMA.TABLES WHERE table_schema = '{{ mariadb_database }}' AND table_name = 'users'"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  register: table_check
>>>>>>> 4f1de76a19322e5fefe44d9c1a20ebec6889f345


