- name: Install MariaDB packages
  apt:
    name:
      - mariadb-server
      - mariadb-client
      - python3-pymysql
    state: present
    update_cache: yes

- name: Ensure MariaDB is started and enabled
  service:
    name: mariadb
    state: started
    enabled: yes
