---
# Ensure artifact_version is set before usage
- name: Set default artifact version if not provided
  set_fact:
    artifact_version: "{{ artifact_version | default('v70') }}"

- name: Download Angular App artifact from S3
  amazon.aws.aws_s3:
    bucket: "cn-jenkins-angular"
    object: "artifacts/angular_app-{{ artifact_version }}.tar.gz"
    dest: "/var/www/html/angular_app-{{ artifact_version }}.tar.gz"
    profile: default
    region: "us-east-2"
  register: s3_download

- name: Create target directory for extraction
  file:
    path: "/var/www/html/angular_app-{{ artifact_version }}"
    state: directory
    mode: '0755'

- name: Extract Angular App
  command: >
    tar -xzvf /var/www/html/angular_app-{{ artifact_version }}.tar.gz
    -C /var/www/html/angular_app-{{ artifact_version }}
  args:
    creates: "/var/www/html/angular_app-{{ artifact_version }}/index.html"
  when: s3_download.changed
  notify:
    - Restart apache2

- name: Create symlink to current deployment
  file:
    src: "/var/www/html/angular_app-{{ artifact_version }}"
    dest: "/var/www/html/current"
    state: link
    force: true

...
