---
# Ensure unzip is installed (Ubuntu/Debian)
- name: Install unzip on Ubuntu/Debian
  apt:
    name: unzip
    state: present
  when: ansible_facts['pkg_mgr'] == "apt"

# Ensure unzip is installed (RHEL/CentOS)
- name: Install unzip on RHEL/CentOS
  yum:
    name: unzip
    state: present
  when: ansible_facts['pkg_mgr'] == "yum"

# Ensure AWS CLI is installed (Ubuntu/Debian)
- name: Install AWS CLI on Ubuntu/Debian
  shell: |
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install
  when: ansible_facts['pkg_mgr'] == "apt"
  args:
    creates: "/usr/local/bin/aws"

# Ensure AWS CLI is installed (RHEL/CentOS)
- name: Install AWS CLI on RHEL/CentOS
  yum:
    name: aws-cli
    state: present
  when: ansible_facts['pkg_mgr'] == "yum"

# Define required directories
- name: Set download and extract directories
  set_fact:
    download_dir: "/tmp/angular_downloads"
    extract_dir: "/tmp/angular_extract"

# Ensure artifact_version is defined (dynamic or hardcoded)
- name: Set artifact version dynamically
  set_fact:
    artifact_version: "{{ lookup('env', 'VERSION') | default('v1.0.0') }}"
    artifact_key: "artifacts/angular-app-{{ artifact_version }}.zip"
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    aws_region: "{{ lookup('env', 'AWS_DEFAULT_REGION') | default('us-east-2') }}"

# Create download and extract directories
- name: Create download and extract directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ download_dir }}"
    - "{{ extract_dir }}"

# Download artifact from S3 (using environment variables)
- name: Download artifact from S3 (using environment variables)
  command: >
    aws s3 cp s3://cn-jenkins-angular/{{ artifact_key }} {{ download_dir }}/artifact.zip
  register: download_result
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
    AWS_DEFAULT_REGION: "{{ aws_region }}"
  args:
    creates: "{{ download_dir }}/artifact.zip"

- name: Handle download failure
  debug:
    msg: "Artifact download failed!"
  when: download_result is defined and download_result.rc != 0

- name: Extract artifact
  unarchive:
    src: "{{ download_dir }}/artifact.zip"
    dest: /tmp/angular-app
    remote_src: yes
    extra_opts: ["-q"]

- name: Check if /var/www/html exists
  stat:
    path: /var/www/html
  register: html_stat

- name: Remove /var/www/html if it exists as a file
  file:
    path: /var/www/html
    state: absent
  when: html_stat.stat.exists and not html_stat.stat.isdir

- name: Create /var/www/html as a directory
  file:
    path: /var/www/html
    state: directory
  when: not html_stat.stat.exists or html_stat.stat.isdir

- name: Copy extracted files to /var/www/html
  copy:
    src: "{{ extract_dir }}/"
    dest: "/var/www/html/"
    remote_src: yes
  notify:
    - Restart apache2
