---
# Fixed task - Use aws_s3 module instead of command to avoid credential issues
- name: Download Angular App artifact from S3
  amazon.aws.aws_s3:
    bucket: "cn-jenkins-angular"
    object: "artifacts/angular_app-{{ artifact_version }}.tar.gz"
    dest: "/var/www/html/angular_app-{{ artifact_version }}.tar.gz"
    profile: default
    region: "us-east-2"
  register: s3_download

- name: Extract Angular App
  command: >
    tar -xzvf /var/www/html/angular_app-{{ artifact_version }}.tar.gz
    -C /var/www/html/angular_app-{{ artifact_version }}
  args:
    creates: "/var/www/html/angular_app-{{ artifact_version }}"
  when: s3_download.changed
  notify:
    - Restart apache2