---
# Fixed task - Use aws_s3 module instead of command to avoid credential issues
- name: Download Angular App artifact from S3
  aws_s3:
    bucket: "cn-jenkins-angular"
    object: "artifacts/{{ artifact_version }}.tar.gz"
    dest: "/var/www/html/"
    profile: default  # Use the default profile
    region: "us-east-2"
  register: s3_download

- name: Extract Angular App
  command:
    cmd: "tar -xzvf /var/www/html/angular_app-v27.tar.gz -C /var/www/html/"
  when: s3_download.changed
  notify:
  - Restart apache2
