---
- name: Create symlink to current deployment
  file:
    src: "/var/www/html/angular_app-{{ artifact_version }}"
    dest: "/var/www/html/current"
    state: link
    force: true
...

#- name: Save current version to file
# copy:
  #  content: "{{ deploy_version }}"
  # dest: "/var/www/CURRENT_VERSION"
    