---
# vars file for Deploy
app_name: angular-app
app_version: "{{ lookup('env', 'BUILD_NUMBER') | default('1.0.0') }}"
deploy_path: /var/www/html
versions_path: /var/www/versions
s3_bucket: "cn-jenkins-angular"
download_dir: "/tmp/angular"
artifact_version: "{{ artifact_version }}"
artifact_key: "{{ artifact_key }}"
